php:
  image: mikeshot/docker-lamp
  container_name: docker-lamp
  volumes:
    - /Users/miguel/protobox:/var/www/html
  links:
    - mariadb
  ports:
    - "80:80"
  environment:
    HOST_IP: 192.168.1.106
    APACHE_DOC_ROOT: /var/www/html
  working_dir: /Users/miguel/protobox

mariadb-data:
  image: tianon/true
  volumes:
    - /var/lib/mysql

mariadb:
  image: mariadb:10.1.10
  volumes_from:
    - "mariadb-data"
  environment:
      MYSQL_ROOT_PASSWORD: root