php:
  image: webgriffe/magento1-dev
  container_name: application-container
  volumes_from:
    - unison
  volumes:
    - "~/.composer:/root/.composer"
    - "~/.ssh:/root/.ssh"
  links:
    - memcached
    - mariadb
    - blackfire_agent:blackfire
  ports:
    - "80:80"
  environment:
    HOST_IP: 192.168.99.1
    APACHE_DOC_ROOT: /unison
  working_dir: /unison

unison:
  image: leighmcculloch/unison
  environment:
    - UNISON_VERSION=2.48.3
  ports:
    - "5000:5000"

mariadb-data:
  image: tianon/true
  volumes:
    - /var/lib/mysql

mariadb:
  image: mariadb:10.1.10
  volumes_from:
    - "mariadb-data"
  environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd

memcached:
  image: memcached

blackfire_agent:
    image: blackfire/blackfire
    environment:
        - BLACKFIRE_SERVER_ID
        - BLACKFIRE_SERVER_TOKEN
        - BLACKFIRE_CLIENT_ID
        - BLACKFIRE_CLIENT_TOKEN